### ISSUE TITLE
Doesn't work on Hass.io anymore.

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-cli#64]
After upgrading to 0.2.0, the CLI doesn't work anymore (changes in #23, #26).

![image](https://user-images.githubusercontent.com/195327/49831620-99ac6780-fd94-11e8-88a8-1b608a79f491.png)

Hass.io Supervisor shows this log:

`18-12-11 21:20:57 WARNING (MainThread) [hassio.api.security] No API token provided for /api/config`

The weird thing is though, `hass-cli info` does not fail (just an empty result):

![image](https://user-images.githubusercontent.com/195327/49831670-c52f5200-fd94-11e8-92fa-f7e0753c89ca.png)

For the record, I do not have `HASS_SERVER` or `HASS_TOKEN` env variables set. Just a (valid) `HASSIO_TOKEN`.

**Comment by maxandersen** [comment]
I got your addon installed, but hass-cli is not installed.
when I try run `pip3 install homeassistant-cli` I get this error:

```
  Using cached https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)
```

I assume you might have some fixes in your dev version of the addon - how would I go about trying that out so I can try reproduce your issue ?

**Comment by maxandersen** [comment]
okey, I managed to reproduce it (using a hass-cli master that doesn't have "exotic" dependencies :)
I'll have it fixed soon - using HASS_SERVER/HASS_TOKEN directly should still work.

**Comment by maxandersen** [comment]
@frenck this should be fixed now in `dev` branch.

You can try it out with `pip3 install https://transfer.sh/1Kn1l/hasscli3.tar.gz`

I ran that in your addon and it then "just worked"

One issue was we had a missing raise on 401, but bigger issue was that the /homeassistant part of http://hassio/homeassistant got remove every time called out - added tests for checking we do it right and fixed it so it should not happen again.

Thanks for reporting the issue and let me know if you find any other issues.

**Comment by scstraus** [comment]
I am still having this problem with the latest version of Frenck's ssh addon for hassio. Was this ever fixed in the addon or should I patch it manually inside the container?

**Comment by frenck** [comment]
@frenck Please report the issue on the add-on repository.
That being said, it just works on my end tbh.

**Comment by scstraus** [comment]
Mine is a bit different. I mainly get the 401:Unauthorized when I am trying to use the autocomplete.. But it does work for a number of operations.

**Comment by frenck** [comment]
Answer stay the same @scstraus, if you have an issue with the add-on, please report it at the add-on repo.

**Comment by haakonstorm** [comment]
I'm getting the same error in my HA 0.92.1 logs:
`[hassio.api.security] No API token provided for /api/config`
Is this related/known or unrelated -- any fix?
